### ISSUE TITLE
TB Version 60 addon?

### ISSUE THREAD

**Issue by Grossdm** [meganz/filelink#1]
Hello,

I noticed that you have updated your repo with "TB 60 compat" - when will we be able to get a binary to install?

TIA
Doug®

**Comment by diegocr** [comment]
We have submitted it to the Mozilla website and it's currently awaiting review, in the next few days should be available to install, thanks for your patience and for using MEGAbird :+1:

**Comment by Grossdm** [comment]
Great, thanks!
